project:
  type: website

website:
  title: "Ethno Archive"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: coulter.qmd
        text: Jeff Coulter
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



